let g:leader = " "

runtime! ftplugin/man.vim

filetype plugin on
filetype indent on
syntax on
set encoding=utf8

set updatetime=500
set timeoutlen=500
set signcolumn=yes
set showmode

set expandtab
set tabstop=8
set softtabstop=4
set shiftwidth=4
set textwidth=100

set autoindent
set smartindent
set copyindent
set hlsearch

set listchars=eol:↵
set list

set splitright
set splitbelow

set nu
set rnu
set mouse=a

set clipboard=unnamedplus
let g:mapleader = " "

map <leader>l :bnext<cr>
map <leader>h :bprev<cr>
map <leader>bd :bdel!<cr>

inoremap jj <Esc>

map H ^
map L g_

map <C-l> :nohlsearch<cr>
