let g:leader = " "

runtime! ftplugin/man.vim

filetype plugin on
filetype indent on
syntax on
set encoding=utf8

set updatetime=500
set timeoutlen=500
set signcolumn=yes
set showmode

set expandtab
set tabstop=8
set softtabstop=4
set shiftwidth=4

set autoindent
set smartindent
set copyindent
set hlsearch

set listchars=eol:↵

set splitright
set splitbelow

set nu
set rnu
set mouse=a

@@ !'thief'
colorscheme delek
@@

set clipboard=unnamedplus
