# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

plugins=(
    uv
    fzf
    starship
    rust
    gitignore
    vi-mode
    zsh-interactive-cd
    sudo
)

source $ZSH/oh-my-zsh.sh

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=10000
setopt autocd extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/zir/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# enable starship
# eval "$(starship init zsh)"

# alisases
@@ 'pyromancer'
export PATH="${PATH}:$HOME/zig-linux-x86_64-0.14.0/"
alias fzf='sk'
alias sus='sudo systemctl start suspend.target && swaylock -c 111111'
alias lock='swaylock -c 111111'
alias yank='wl-copy'
alias past='wl-paste'
alias menu='menuscript | sk | xargs ~/.local/bin/menuscript'
alias cdf='res=$(fd . ~ -t d | sk --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden); if [ -n "$res" ]; then cd "$res"; fi'
alias Vi='sudoedit'
@@
alias ls='exa'
alias vi='nvim'
alias nssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias mute='pactl set-sink-volume 0 0%'
alias grep='rg'
alias ff='find -type f ! -name ".*" ! -path "*/.*" | fzf'
alias cswp='rm ~/.local/state/nvim/swap/* && rm ~/.local/state/nvim/log'
alias g='git'
alias dots='cd ~/clones/dotfiles/ && vi . && der2 -avRs && cd -'
alias wiki='(cd ~/wiki/ && nvim +"WikiIndex")'
@@ !'pyromancer'
alias yank='xsel -ib'
alias past='xsel -ob'
@@
alias cdf='res=$(fd . ~ -t d | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden); if [ -n "$res" ]; then cd "$res"; fi'
alias lg='lazygit'

if [[ ! "$(tty)" = "/dev/tty1" ]]; then
    if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
      exec tmux -u
    fi
fi

bindkey -M viins 'jk' vi-cmd-mode
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
